apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env: 
          - name: WORDPRESS_DB_HOST
            value: mysql-svc
          - name: WORDPRESS_DB_USER
            value: exampleuser
          - name: WORDPRESS_DB_PASSWORD
            value: examplepass
          - name: WORDPRESS_DB_NAME
            value: exampledb
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env: 
          - name: MYSQL_DATABASE
            value: exampledb
          - name: MYSQL_USER
            value: exampleuser
          - name: MYSQL_PASSWORD
            value: examplepass
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: '1'
